version: "3.8"
services:
  api:
    build: ./
    container_name: server
    ports:
      - '5000:5000'
    env_file:
      - .env
  myblog:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
    stdin_open: true
    links:
      - 'api'